# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Azure Resources and Application
# See readme file for info about variable group 'OpenAISearch'
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  #   exclude:
  #     - '**/*.md'
  # paths:
  #   include:
  #     - 'app/*'

# ----------------------------------------------------------------------------------------------------
# This approach to optionally deploy QA works but it's not DRY
# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/infra-and-website-pipe.yml
  parameters:
    variableGroupName: 'OpenAISearch'
    environments: ['DEV'] # ['DEV','QA', 'PROD']
    appFolderName: 'app'
