# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy Website Only
# See readme file for info about variable group 'OpenAISearch'
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

pool: Default
  # vmImage: ubuntu-latest

# ----------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  # - none
  # batch: true
  # branches:
  #   include:
  #     - main
  paths:
    include:
      - 'app/*'
# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/website-only-pipe.yml
  parameters:
    variableGroupName: 'OpenAISearch'
    environments: ['dev']
    appFolderName: 'app'
