# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build and deploy Azure Resources and Application
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEMO']
- name: variableGroupName
  default: 'myVariableGroupName'
- name: appFolderName
  default: 'app'
- name: runDevSecOpsScan
  default: 'false'
- name: runPsRuleScan
  default: 'false'

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if or(eq(lower(parameters.runDevSecOpsScan), 'true'), eq(lower(parameters.runPsRuleScan), 'true')) }}:
  - stage: ScanApplication
    displayName: Scan Application
    jobs:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEMO'
        runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
        runPsRuleScan: ${{ parameters.runPsRuleScan }}

# ----------------------------------------------------------------------------------------------------
- stage: BuildApplication
  displayName: Build Web App
  jobs:
  - template: templates/build-website-template.yml
    parameters:
      variableGroupName: ${{ parameters.variableGroupName }}
      environmentName: 'DEMO'
      appFolderName: ${{ parameters.appFolderName }}

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: CreateInfra${{ environmentName }}
    displayName: Create ${{ environmentName }} Resources
    dependsOn: BuildApplication
    condition: succeeded('BuildApplication')
    jobs:
    - template: templates/create-infra-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: ${{ environmentName }}

  - stage: Deploy${{ environmentName }}App
    displayName: Deploy ${{ environmentName }} App
    dependsOn: CreateInfra${{ environmentName }}
    condition: succeeded('CreateInfra${{ environmentName }}')
    jobs:
    - template: templates/deploy-website-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: ${{ environmentName }}

  - stage: Update${{ environmentName }}Search
    displayName: Update ${{ environmentName }} Search
    dependsOn: Deploy${{ environmentName }}App
    condition: succeeded('Deploy${{ environmentName }}App')
    jobs:
    - template: templates/update-search-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: ${{ environmentName }}
